### ISSUE TITLE
Consider offering a ligatures version?

### ISSUE THREAD

**Issue by neonpixii** [jackhumbert/sitelen-pona-pona#2]
I adore the readability and pleasant design of this font and would love to use it in a word processor. It would be useful to have a alternative version of the font that uses ligatures to automatically convert valid toki pona words into sp glyphs, the way linja pona does. 

this would possibly interfere with certain non-toki pona words, but i imagine you could get around that by having an "escaped" version of valid toki pona words, that *dont* ligature. for instance, if you needed to write "Ike" (the name), but dont want it to be converted into the ike glyph, perhaps you could do something like \ike, where the \ gets hidden by ligatures, to bypass the toki ponaization.

**Comment by jackhumbert** [comment]
This should be possible with the `salt` table (stylistic alternative) enabled in your word processor - that's what is happening in the textarea at the bottom of the demo page: https://jackhumbert.github.io/sitelen-pona-pona/

Any captialised words don't ligature, so `Ike` would be displayed with the cartouche :)

**Comment by neonpixii** [comment]
the word processor i use does not have a salt feature, which is why i think that having a ligatures version is a good idea for the sake of including everybody in this great font

ligatures are very widely compatible and work "out of the box" with most programs, wheras salt does not seem to be, given that its not a feature in many (or even most?) text editors and word processors

**Comment by jackhumbert** [comment]
`salt` is just a type of ligature :) the ligatures that people are used to are usually just in the `liga` table, which is usually enabled by default - I've give some thought to just moving things over to `liga` so that things could be a bit more widely implemented like, and I think it's worth giving a shot! I'll make those changes and push things up soon.

**Comment by neonpixii** [comment]
i'm not sure what a lot of that said, i'm not very aware of how fonts work, 

but my point is that while ligatures in linja pona work fine in both notepad and focuswriter (and really just anywhere i've enabled it, ligatures in sitelen pona pona do not function in either of those apps. for the sake of compatibility with a more wide ranging group of apps it might be sensible to offer a version of the font that uses the same sort of technology that linja pona uses, so that it is more widely compatible with apps that dont have a wide range of cutting edge features.

if liga is indeed what linja pona uses, and would work in most apps where salt seems to not work, then, yay! thank you for all the hard work!

**Comment by jackhumbert** [comment]
I just made this change and published the font under v0.2: https://github.com/jackhumbert/sitelen-pona-pona/releases/tag/v0.2 would you be able to test it out?

**Comment by neonpixii** [comment]
it seems to work great in both notepad and focuswriter!

**Comment by neonpixii** [comment]
oh: there does seem to be a bug with certain proper names

in a document i was working on, "ma Nave" shows up as "⊕ [NA]V»" when it should show up as "⊕ [Nave]"

**Comment by jackhumbert** [comment]
Ah, yeah - I don't think I have any consideration for letters that aren't in toki pona :) I think I can add support for these, though!

**Comment by neonpixii** [comment]
i think that support for them should probably be added because 
1) i'm fairly sure its pu to use non-toki pona letters in proper names of things, especially when you'll be more readily understood than if you pona-ized the name
2) even if its not pu, its strongly common practice in toki pona communities anyways, and 
3) the font already has characters for the non-tp letters so they may as well be fuly supported as first-class members of the font

if this needs to have a new issue made i can make a new issue

**Comment by jackhumbert** [comment]
Added these in 7dc22cb :)
