### ISSUE TITLE
Add support for the tonsi glyph

### ISSUE THREAD

**Issue by neonpixii** [jackhumbert/sitelen-pona-pona#3]
Given the recent survey showing a strong community concensus on the tonsi glyph (https://www.reddit.com/r/tokipona/comments/gmhzgg/survey_results_how_much_people_likeddisliked/), as well as the addition of the tonsi glyph to the sitelen linja font, the tonsi glyph should be added to this font.

**Comment by jackhumbert** [comment]
Awesome! I'll get that added :)

**Comment by jackhumbert** [comment]
How's this look? I think it makes sense to style it similarly to mije and meli, right?
![image](https://user-images.githubusercontent.com/141431/83681975-3bd79500-a5b1-11ea-8400-d9f66885e7ab.png)

**Comment by jackhumbert** [comment]
Adding this as well :)
![image](https://user-images.githubusercontent.com/141431/83682189-940e9700-a5b1-11ea-8e7d-eb00c98d50a0.png)

**Comment by neonpixii** [comment]
both of those look fantastic!

**Comment by jackhumbert** [comment]
Awesome, added in 7dc22cb :)
